import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-4 right-4 z-50">
          <select
            className="border rounded px-3 py-1 bg-white text-gray-800 shadow"
            onChange={e => {
              if (e.target.value) window.location.href = e.target.value;
            }}
            defaultValue=""
          >
            <option value="" disabled>언어 선택 / 言語選択</option>
            <option value="/ko">🇰🇷 한국어</option>
            <option value="/ja">🇯🇵 日本語</option>
          </select>
        </div>
        {children}
      </body>
    </html>
  );
}
